version: '3.5'

services:

    employee-records-auth:
        image: auth
        build: ./auth
        ports:
            - "3334:3334"
        restart: always
        hostname: employee-records-auth
        networks: 
            - auth
    
    employee-records-backend:
        image: backend
        build: ./backend
        ports:
            - "3333:3333"
        restart: always
        hostname: employee-records-backend
        networks: 
            - backend

networks:
    
    auth:
        name: employee-records-auth
        driver: bridge
    
    backend:
        name: employee-records-backend
        driver: bridge